### ISSUE TITLE
Differentiation of phishing-resistant authentication at AAL2

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#3]
NIST recognizes that mis-authentication due to phishing attacks is an important problem. The verifier impersonation resistance requirement at AAL3 provides phishing resistance by denying an attacker the ability to reuse an authenticator output they obtained through a phishing attack on an unwary Subscriber. However, there is no similar requirement at AAL2, which is used for many sensitive transactions, particularly those initiated by members of the public.

One possible option is to require phishing resistance for all authentications at AAL2. However, this may not be practical because it would only allow the use of a subset of cryptographic authenticators, and effectively obsolete other classes of physical authenticators. It would also require that authenticators connect directly (via wired connection) to associated endpoints, which is sometimes not permitted due to other security concerns. For these reasons, NIST is inclined to make authenticators and authentication processes that provide phishing resistance a recommendation at AAL2. 

NIST is interested in feedback on  specific use cases where phishing resistance should always be required that are not suitable for AAL3.

**Comment by JayMMeier** [comment]
In our spoof-bounty program, we observe two types of phishing attacks.  First, attackers attempt to decrypt & edit the contents of identity related payload data, to contain synthetic data not collected from the session, to have the Server process and respond with Liveness and Matching Success.  Second, attackers attempt to take over the camera feed & inject previously captured video frames or a deepfake puppet that results in successful fraudulent enrollment or authentication.  These attacks can be defeated by cryptographically securing the camera and video frame feed data.

**Comment by The-FIDO-Alliance** [comment]
We are pleased to see NIST focusing on this topic.  As we flagged in our comments to NIST last August, MFA adoption has been steadily increasing over the last 10 years – and with it, so have attacks seeking to defeat or circumvent MFA. As such, we strongly believe NIST should recommend phishing resistance for authenticators and authentication processes a recommendation at AAL2.

NIST rightly flagged the security limitations of SMS in its last revision of SP 800-63, starting with drafts in 2016 that highlighted the ways in which attackers had caught up with SMS.  NIST’s work here helped to prompt organizations across the globe to move away from SMS and embrace more secure authentication tools. 

In 2021, it’s time for NIST to sound the alarm again.  Attackers have moved on to compromises of other authentication tools that are also based on shared secrets, including both OTP and push-based solutions.  Here, we’ve seen a sharp increase in the number of phishing attacks looking to trick users into either handing over their OTP codes or approving a request from a push notification that has been activated as part of a phishing attack.  

If attackers can trick users into typing in a password, they can also trick them into sharing a six digit code or approving a request in a push-based authentication app. 

As a result, leaders in the security community have begun to move away from OTP and other authentication tools based on “shared secrets.” The industry is shifting toward “high assurance” MFA where at least one factor is based on public key cryptography, and thus resistant to phishing.  Authentication using the FIDO standards is one such example. 

This is an area where we believe the current version of SP 800-63-3 needs some updates.  Today, a variety of authenticators based on shared secrets – including look-up secrets, out-of-band devices (i.e., app push), and OTP apps and tokens – are given the same weight in AAL2 as authenticators based on asymmetric public key cryptography.  Given how attackers have caught up with the former, it no longer makes sense to list these two types of authenticators alongside each other. 

Doing so misleads implementers into thinking that these two categories of authenticators are still equivalent in strength or resiliency.  Going forward, NIST should adjust its approach to AALs to help implementers clearly differentiate between tools that are phishing resistant and those that are not. 

We are pleased to see NIST indicate an interest in making authenticators and authentication processes that provide phishing resistance a recommendation at AAL2.

We believe the **best** approach here would be for NIST to create an “AAL2+” designation that would differentiate between AAL2 tools that are phishing resistant and those that are not.  This approach would allow NIST to keep the three levels of AALs while effectively differentiating between authentication tools based on shared secrets and those based on asymmetric public key cryptography. 

By pairing the creation of an AAL2+ category with a recommendation to use AAL2+ authentication whenever feasible, NIST would send a clear message to implementers - both in agencies and in the private sector - that these technologies are different and more secure.  

We are concerned that if phishing-resistance is only a recommendation - and that phishing-resistant and phishable authenticators continue to be grouped together in the same AAL2 category - that the market will ultimately be confused.  
We note that some stakeholders may have concerns that creating a “+” category here might confuse agencies and other implementers looking to use the risk assessment framework in SP 800-63-3 to select the appropriate assurance level.  That said, we believe it would be very straightforward for NIST to maintain the current framework and simply say “Use AAL2 – and ideally/if feasible, AAL2+.” 

Additionally, we believe NIST should consider calling for any **new** deployments of AAL2 solutions to use phishing-resistant authentication based on asymmetric public key cryptography.  This would allow legacy AAL2 systems to continue to stay in place while ensuring that any new dollars invested in authentication tools are used on more secure authentication systems.

**Comment by jimfenton** [comment]
@The-FIDO-Alliance In order to justify the creation of an AAL2+, it would need to be required for specific use cases (risk profiles) that do not justify AAL3, as mentioned in the last paragraph of the issue. Are there such use cases? If not, rather than create a separate AAL2+ category, it would be sufficient to recommend the use of phishing-resistant authentication at AAL2.

**Comment by The-FIDO-Alliance** [comment]
Thanks Jim.  We're looking at this a bit differently.  It's not about use cases that don't justify AAL3, but rather a way to signal to implementers more clearly that AAL2 authenticators with the "+" designation are better.  

As we noted above, we are concerned if phishing-resistance is only a recommendation - and that phishing-resistant and phishable authenticators continue to be grouped together in the same AAL2 category - that the market will ultimately be confused.  

The two types of authenticators really don't belong in the same category, given how attack vectors have changed.  Our concern is that if phishing resistance recommendations are relegated to a footnote or implementation detail, the message won't be clear to implementers.  Thus our suggestion that NIST maintain the current framework and simply say “Use AAL2 – and ideally/if feasible, AAL2+.”

Another way to think about this: we're not recommending a new AAL, just a mark that can differentiate how these different types of authenticators co-exist in the AAL2 universe while still being different.

**Comment by ve7jtb** [comment]
@jimfenton 

It is hard to argue that any authentication should be allowed to not be phishing resistant.
I understand why creating a new level is problematic.  I am not a big fan of + levels myself.

I think that in 800-63-4 NIST should signal an intent to deprecate methods that don't incorporate strong cryptographic phishing resistance on the primary access channel.  The goal would be to get new deployments to implement those methods while giving existing implementations notification that they need to start looking at alternatives without immediately putting them out of compliance.

We are now familiar with  evilginx2[https://github.com/kgretzky/evilginx2](url) and many other tool kits that allow hijacking of session cookies.  Many of the AAL2 methods are vulnerable to that.   I think part of this is to educate RP that push notification apps like Microsoft Authenticator, Google Authnticator and many others are not resistant to these attacks even if they are marketed as passwordless.   The goal of the attacker is to get access to a session at the RP as the user, if they can do that without getting the password itself then these authentication methods are just conveniences for the user and real anti phishing solutions.

John B.

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.
