### ISSUE TITLE
Requirements for wireless authenticators

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#4]
The use of short wireless technologies, particularly NFC, Bluetooth, and Bluetooth LE, is an attractive way to connect physical authenticators, particularly cryptographic authenticators, to endpoints to complete an authentication transaction. However, as compared with a wired connection to the endpoint, a wireless connection presents a new opportunity for an attacker to eavesdrop on, perform an in-the-middle attack on, or even surreptitiously access an authenticator to facilitate an unauthorized authentication. If the activation factor for a multi-factor wireless authenticator is entered on the host endpoint, there is also the potential for that factor to be leaked if not sufficiently protected in transit.

NIST is considering additional requirements for the use of authenticators that are wirelessly connected to their endpoints, such as: 

- requiring authentication intent, 
- strong replay resistance,
- requiring a pairing process with the authenticator prior to authentication, 
- timing restrictions on the authentication transaction process.

NIST would appreciate any examples where these new requirements would interfere with the desired use of a wireless authenticator, and whether any of these require computation or transaction complexity that would be difficult to implement on certain authenticator types (such as remotely powered NFC).

**Comment by JayMMeier** [comment]
Does this question refer exclusively to physical authenticators that communicate wirelessly to an endpoint, to deliver determined authenticator match results to the endpoint?  Or could this include any identity related payload data, delivered wirelessly to an endpoint (potentially to be processed off the wirelessly device)?

**Comment by jimfenton** [comment]
This issue pertains to wireless communication directly between an authenticator and an associated endpoint. Information sent over this interface might include a challenge nonce, information about the identity of the verifier, and perhaps an activation value (PIN or biometric data) if presented at the endpoint.

As mentioned in the issue, security concerns include eavesdropping and in-the-middle attacks on the endpoint-authenticator interface as well as more specialized classes of these like relay attacks.

**Comment by The-FIDO-Alliance** [comment]
We agree in principle with these requirements, but it’s important to note that not all wireless technologies are created equally. Mechanisms that have inherent limits on proximity of activation (such as NFC and UWB) behave much more like “wired” devices and as such might not have a need for any additional requirements over what “cabled” authenticators should already satisfy.

Authenticators using wireless technologies which inherently require “disambiguation” (ie. it’s assumed that more than one “authenticator-host” pair can be in range at the same time), such as Bluetooth, will require the four points noted above - in FIDO2, you need encryption of the CTAP messages as to not violate the user’s privacy.

As such, it may make sense for NIST to spell out specific requirements for specific wireless transports.

**Comment by jimfenton** [comment]
Proximity of activation is of course an important consideration. However, there is concern about relay attacks (where an attacker is able to covertly place a reader near the authenticator and activate it in real time); these are mitigated by the use of short-range technologies, but it is not entirely clear that no risk remains. As mentioned above, there is also concern about eavesdropping attacks to obtain an activation secret that may be sent from the endpoint to the authenticator. The interception range for NFC is considerably greater than the activation range.

**Comment by christiaanbrand** [comment]
Indeed. I do wonder about the practicality of pulling off an attack here based on "interception": the *real user* will establish a session with a relying party and will receive some data (which includes a nonce) to relay to the security key. If an attacker gets hold of that data in transit (or even the response from the security key) it should _not_ be possible for them to simply send it to the relying party (as the response will be expected only from the host who made the request in the first place). 

Maybe the consideration here should rather be that a relying party "bind" the request and the response together in the same session (using a cookie, etc) so that it only works if both are received/sent by the same party? I feel like this is especially important when FIDO is used in "sole factor mode".

**Comment by jimfenton** [comment]
Note that we aren't just concerned with attacks that directly result in misauthentication, but also attacks that leak information that may be of value. For example, if the activation secret (typically PIN) for a multi-factor authenticator is entered on the endpoint and then sent to the authenticator in the clear, there might be an opportunity for an attacker to obtain one of the authentication factors (and then perhaps steal the physical authenticator).

This is just an example; any manner in which using a wireless authenticator could be weaker than using a contact interface would be of interest.

**Comment by huzzeytech** [comment]
We suggest there be slightly varying authentication intent requirements dependent on the equipped protocol. NFC authentication intent from the user takes place as the authenticator is brought within the limited range of <10cm by spec and <5cm by practice. To strengthen the intent, the authenticator should be unpowered or classified as a passive device with no onboard power. In this case, acting as a transponder, the authenticator is only powered while brought in range of the initiator device or authentication endpoint. Lastly, for higher security requirements such as AAL2 or AAL3, intent should be enforced through a PIN. That PIN (activation secret) should be encrypted en route to the authenticator.
 
Given the increase in adoption of wireless protocols in authentication endpoints, we support the creation of the additional requirements for strong replay resistance and timing restrictions regardless of the transport protocol. That being said this may have to do more with a properly configured Relying Party than the authenticator itself.
 
The additional requirement of a pairing process should apply to Bluetooth but not NFC given there is no established NFC pairing concept.

**Comment by ve7jtb** [comment]
@jimfenton 

In Fido2 the pinUvAuth protocol encrypts the pin and any returned access tokens using ECDH derived keys. 

CTAP2.1 adds a FIPS-approved version of the pinUvAuth protocol specifically so it can be used over wireless connections where the PIN must be encrypted.

If authentication is used then each command to the authenticator is integrity protected and can't be tampered with and replayed.  (over NFC if you start a new session the ECDH keys and access tokens are regenerated stopping replay.

As @christiaanbrand states, propper use of single use challenges would prevent someone reading the NFC field at a distance from being able to replay the assertion/token and have it accepted.   Yes if the browsers implemented RFC 8471-8473 then that would also have prevented replay from a different user agent, but such is life, we have the challenge and that works.

John B.

**Comment by MelanieTiano-CTIA** [comment]
Please find attached the comments of CTIA.
[Comments of CTIA to NIST re Digital Identity Guidelines Open Issues.pdf](https://github.com/usnistgov/800-63-4/files/6480851/Comments.of.CTIA.to.NIST.re.Digital.Identity.Guidelines.Open.Issues.pdf)

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.
