### ISSUE TITLE
Requirements to strongly bind assertions to authenticated sessions at FAL3

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#6]
The definition of FAL3 in 800-63C-3 requires the subscriber to present proof of possession of a key referenced in the assertion presented to the RP. The goal of this requirement is to strongly bind an authenticated session for the subscriber with an assertion representing that subscriber. This pattern allows an RP to have a high confidence in the identity of the current subscriber while still outsourcing the major identity account functions to the IdP. 

The current requirements are based on industry experience using SAML with a PKI-backed credential, in which the subscriber would authenticate to the IdP using a PKI certificate (such as a PIV Card), and then be able to present that certificate again to the RP alongside the assertion, which would contain a reference to the subscriber’s certificate. At the time of publication, several new technologies were on the horizon, and it appeared that this pattern of including a key reference in the assertion to be verified by the RP would be possible with a variety of these new systems. As such, we positioned FAL3 as achievable but mostly forward-looking, in anticipation of coming changes.

However, it has turned out that the cryptographic authenticator market has not gone in this direction, and in fact critical privacy-focused aspects of these authenticators make it very difficult to achieve FAL3 using them. Specifically, it is against the prevailing authenticator protocol design to allow the IdP to know the key the subscriber would use at the RP as doing so would allow collusion between two separate hosts. It is possible for a subscriber to present an authenticator to an RP alongside an assertion, but the requirement of having the authenticator’s key reference embedded in the assertion is actively blocked by these technologies, since sharing keys between hosts is forbidden.

In order to make FAL3 achievable using a variety of today’s technologies, NIST is considering changes in SP-800-63C-4, including: 

- Redefine FAL3 to require presentation of a bound cryptographic authenticator, but relax the requirement of the assertion containing the key of the authenticator. This would leave the RP in charge of managing the binding, and the IdP would likely have no knowledge of the authenticator used.
- Extend existing (and future) federation protocols to allow an RP to push a bound authenticator’s key back to the IdP. This would allow the IdP to know the authenticator, but it would require significant retooling for protocol support and similar previous efforts (such as referred token binding) have not seen any adoption.
- Require the use of the same key at the IdP and RP. This is effectively the case with FAL3 today, and it implies a PKI style credential since it is usable across different hosts.

NIST is seeking input into the viability of these approaches and will consider suggestions for alternative approaches that can achieve a high level of trust at FAL3 but still be accessible to today’s technology systems.

**Comment by EhudItshaki** [comment]
I'd like to propose NIST to consider including the use of a cryptographic key tied to a device or an app. Such key could be protected at different levels (software, hardware, hardware and verifiable by IdP/RP) and bounded at different times (registration, token issuance). While this doesn't offer the same level of protection as requiring the subscriber to present proof of possession, it does provide for a much better user experience and confines the use of such protected tokens to the same endpoint.

**Comment by Yubi-David** [comment]
Much like the AAL3, there seems to be little wiggle room here. In the absence of Token Binding, NIST is again at a crossroads and in need of new technology. In the current environment we do not believe that the options suggested by NIST offer a viable path to adopt.
In regards to NIST’s second bullet point in its #6 GitHub comment section, it points out that changes to allow the IdP to know the authenticator would require significant re-tooling for protocol support. In addition, significant work is needed to create an acceptable UX. Previous work in this realm by the IETF resulted in OAuth 2.0 Demonstration of Proof-of-Possession (DPOP), but this work also suffers from limitations and is not a complete solution. FIDO2 does offer a possible path, but there are challenges with origin binding. 
Maybe the question going forward is how do we break down this knowledge and build up answers to NIST’s needs. Can there be Vendor Impersonation Resistance via Audience Restricted Tokens, and have RPs protect the private keys for certification and check certification logs?
-David Maples, Yubico

**Comment by jricher** [comment]
To clarify, the bullet points above are several different approaches that NIST is considering in response to this issue, not necessarily recommending all of them together as a packaged solution. As mentioned in the comments here, there are limitations and tradeoffs with each one, and if any of the above changes are incorporated, these tradeoffs would need to be discussed.

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.
